research_task:
  agent: senior_researcher
  description: >
    Conduct an in-depth investigation into {guest}, gathering relevant
    information from various sources. Focus on their background, education,
    career milestones, public image, notable achievements, personal life,
    influence and impact, challenges and controversies, publications and works, 
    awards and honors, philanthropy and activism, and current projects.
  expected_output: >
    A highly detailed and well-structured report in markdown format detailing
    the life and career of {guest}, including: Background, Education, Career
    Milestones, Public Image, Notable Achievements, Personal Life, Influence and
    Impact, Challenges and Controversies, Publications and Works, Awards and
    Honors Philanthropy and Activism, Current Projects. The report should have a
    title (i.e., "#") and subtitles (i.e., "##"). Don't start the report with a
    sentence like "Here is the detailed report on Rok Benko:". Just start with
    the heading (i.e., "#") and then the content. Each section should have as
    much content as possible but never make up content. Content should be
    fact-based information from the {guest} research. Additionally, all links
    to sources used in the research should be included at the end of the report
    for reference.
