calculate_cost:
  agent: senior_mathematician
  description: >
    Calculate the cost of CrewAI usage based on {usage_information} by utilizing
    Python. All usage is based on the Anthropic Claude 3 Haiku model, which
    costs $0.25 / 1 million input tokens and $1.25 / 1 million output tokens.
    Write and execute Python code to make calculations. The calculated number is
    just an estimated cost because Cost Calculation crew itself also uses some
    tokens that are not included in the {usage_information} although a lot less
    than other crews. There are two CrewAI crews that are included in
    {usage_information}: Guest Research crew and Questions Research crew.
  expected_output: >
    A highly detailed and well-structured report in markdown format, containing
    details about usage and costs. The report should be structured into four
    sections: - Guest Research Crew Cost: Provide the detailed costs associated
    with the Guest Research Crew. - Questions Research Crew Cost: Include the
    costs incurred by the Questions Research Crew. - Total Cost: Summarize the
    total cost by adding the costs of both crews. - Code Used for Calculations:
    Include the Python code used for performing the cost calculations. At the
    bottom add the following note: "*Note: The calculated cost is an estimate
    because the Cost Calculation crew also uses some tokens that are not
    reflected in the initial calculation shown above. These costs are excluded
    because the exact number of tokens used by this crew is only available after
    execution (i.e., when you're reading this). However, the token usage is
    expected to be minimal. To get the complete total, you can manually add the
    Cost Calculation crew's token usage from the `log_token_usage.txt` file to the
    Total Cost calculated by CrewAI.*"
