cost_calculation_task:
  agent: senior_mathematician
  description: >
    Estimate the cost of CrewAI usage using {usage_information} with Python. The
    calculations will be based on the Anthropic Claude 3.5 Sonnet model, which
    charges $3 per million input tokens and $15 per million output tokens. Write
    and execute the Python code for these calculations. Note that the estimated
    costs may not reflect the full expense since the Cost Calculation crew also
    consumes some tokens not included in the usage_information, albeit
    significantly less than other crews. Additionally, the Exa tool incurs costs
    that are not captured in the usage_information, as the API does not provide
    usage data. The usage_information includes two CrewAI crews: the Guest
    Research crew and the Questions Research crew. Ignore the "Successful
    Request" count in the usage_information for the calculations; only consider
    "Input Tokens" and "Output Tokens." However, include the "Successful
    Requests" for both crews in the markdown report for informational purposes.
  expected_output: >
    A highly detailed and well-structured report in markdown format, containing
    details about usage and costs. Please clearly indicate it's just an
    estimated cost since the Cost Calculation crew and Exa are not included in
    the usage data. The report should be structured into four sections: - Guest
    Research Crew Cost: Provide the detailed costs associated with the Guest
    Research crew. - Questions Research Crew Cost: Provide the detailed costs
    associated with the Questions Research crew. - Total Cost: Summarize the
    total cost by adding the costs of both crews. - Code Used for Calculations:
    Include the Python code used for performing the cost calculations. The
    report should have a title (i.e., "#") and subtitles (i.e., "##"). At the
    bottom, include a note clearly stating that the reported costs are
    estimates due to the consumption of tokens by the Cost Calculation crew and
    Exa tool, which are not accounted for in the usage data.
